### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#1]
This issue consists of on the one hand properly displaying errors to the user while hiding the internals of the application (such as the web assembly parts) by filtering stack traces, and on the other hand catching anything that could go wrong. A list of example code files that should be handled are found in https://github.com/dodona-edu/universal-judge/issues/19. 

- [ ] Hide internals (wasm, unknown file, ...)
- [ ] Display errors in an expected fashion
- [ ] Handle common errors properly

**Comment by winniederidder** [comment]
Relevant library to aid students and myself when print debugging: https://github.com/gruns/icecream

**Comment by pdawyndt** [comment]
You might also have a look at the [Rich](https://github.com/willmcgugan/rich) module.

**Comment by alexmojaki** [comment]
For displaying error tracebacks in user code to students, I suggest https://github.com/friendly-traceback/friendly-traceback:

- Nicer formatting (optionally using Rich!)
- Beginner-friendly explanations
- Supports three languages and has a solid i18n framework in place, I'm sure they'd appreciate a Dutch translation!

**Comment by alexmojaki** [comment]
Also, the current tracebacks don't include the user's source code, just something like `File "<exec>", line 1, in <module>`. To make the source code appear, you need something like this:

```python
    filename = "my_program.py"
    linecache.cache[filename] = (
        len(code),
        0,
        [line + '\n' for line in code.splitlines()],
        filename,
    )
    code_obj = compile(code, filename, "exec")
    exec(code_obj)
```

**Comment by winniederidder** [comment]
> Also, the current tracebacks don't include the user's source code, just something like `File "<exec>", line 1, in <module>`. To make the source code appear, you need something like this:
> 
> ```python
>     filename = "my_program.py"
>     linecache.cache[filename] = (
>         len(code),
>         0,
>         [line + '\n' for line in code.splitlines()],
>         filename,
>     )
>     code_obj = compile(code, filename, "exec")
>     exec(code_obj)
> ```

I'll take a look at how this works along with libraries such as doctest, as I encountered some issues with that when calling exec myself. Those might be resolved or not be present in your approach.

**Comment by alexmojaki** [comment]
Now that I think of it, writing directly to linecache is not necessary for you, you can just write the contents of `code` to a file located at `filename` and get the same result. It's basically the same thing but it looks less mysterious.

**Comment by winniederidder** [comment]
> Now that I think of it, writing directly to linecache is not necessary for you, you can just write the contents of `code` to a file located at `filename` and get the same result. It's basically the same thing but it looks less mysterious. I originally used `linecache` back when futurecoder ran on a server and I had restricted filesystem access.

I believe I found an even better way to handle this case. The pyodide module provides a method eval_code_async. In JavaScript, it is not as easy to configure, but you can do this within Python itself. This allows passing a filename and other options to the compile call, without having to do anything mysterious yourself. As a bonus, this allows async code to also still work.

For example, the following code on FutureCoder#ide does not yield any output:
```python
async def main():
    import micropip
    await micropip.install('snowballstemmer')
    import snowballstemmer
    stemmer = snowballstemmer.stemmer('english')
    print(stemmer.stemWords('go goes going gone'.split()))

main()
```

whereas it does yield ['go', 'goe', 'go', 'gone'] when run via eval_code_async. This might thus be something you want to integrate in FutureCoder aswell? Let me know your thought.

**Comment by alexmojaki** [comment]
It seems like different things are being mixed up. I see in the PR you took the suggestion to write the source code to a file, and that solved the traceback problem (and probably the doctests issue). `eval_code`/`eval_code_async` doesn't do that, but that's fine, it's basically replacing the last two lines containing `compile` and `exec`. The 'mysterious' code that I was referring to was the `linecache` part, not `compile`.

> For example, the following code on FutureCoder#ide does not yield any output:

That code isn't really *supposed* to work. If I run it in normal Python locally I get `RuntimeWarning: coroutine 'main' was never awaited` and the function doesn't actually run, even if it's just a simple `print` with nothing else. I think what's happening here is that `eval_code_async` returns the last expression which is `main()` and then Papyros `await`s the result. Adding another expression after the `main()` prevents this from happening so nothing is printed. Passing `return_mode='none'` to `eval_code_async` should also prevent this.

`eval_code` (and thus also `runPython`) without the `_async` does the same thing, `eval_code_async` just allows using top level `await`. That means you can write `await main()` at the end, and that should run the function regardless of `return_mode`. So that feels a bit more like code that's 'supposed' to work, except of course in normal Python the top-level await would be a syntax error.

> This might thus be something you want to integrate in FutureCoder aswell

I don't think `eval_code_async` is sufficient. On the one hand, top-level `await` is nice and convenient and lowers the barrier to entry. On the other hand, asyncio is confusing and mysterious (I don't quite understand it myself) and I'd be worried about adding to that confusion by teaching something that doesn't work in normal Python.

So I'd at least want to say "we've added some magic to make things easier, but in real life you need to use something like `asyncio.run(main())`." But that doesn't work in Pyodide either, and neither does e.g. `asyncio.get_event_loop().run_until_complete` or `run_forever` - see https://github.com/pyodide/pyodide/blob/17f675a89e28aa17d0b9c9697cf0a49402c4de53/src/py/pyodide/webloop.py. Making asyncio work 'realistically' ironically requires synchronous IO, a generalisation of the `input()` stuff. Hopefully that will eventually be part of Pyodide itself, but until then I imagine it being part of the generic futurecoder-Pyodide backend module I've talked about.

As for your code example, this is sufficient in futurecoder:

```python
import snowballstemmer
stemmer = snowballstemmer.stemmer('english')
print(stemmer.stemWords('go goes going gone'.split()))
```

futurecoder automatically detects the import and installs it with micropip itself. That's also a feature of the generic backend. But this doesn't work for dynamic imports or imports that happen inside other packages (see https://github.com/alexmojaki/futurecoder/issues/182). Maybe that could also be solved with synchronous IO.

**Comment by winniederidder** [comment]
Thank you for your detailed response! 
For now, I think we want to allow top level awaits as they are convenient, not that I expect many people to use async/await.
The automatic importing sounds very useful and user-friendly, so I'll take a look at that aswell.

**Comment by alexmojaki** [comment]
Top-level await is fine, but I do think it's important to pass `return_mode='none'` to `eval_code_async` so that `await` is consistently needed. The fact that `main()` on its own works but only as the last expression is a bug IMO.

**Comment by alexmojaki** [comment]
Oh, I just tried and I see it doesn't work anymore. Probably because you're not returning from `eval_code_async`, so that's fine. Just update that async code example.
