### ISSUE TITLE
Resizing online documentation window does not work properly

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#120]
On naos, resizing the window showing the online documentation upon code completion does not work properly. The window may also run outside the viewport for large documentation (e.g. `testmod` from the `doctest` module).

**Comment by winniederidder** [comment]
I opened an issue regarding the resizing over on [CodeMirror](https://github.com/codemirror/codemirror.next/issues/815).
Since Papyros is drawn on the right side of the screen, the autocompletions often appear on the left side of the editor, where resizing properly requires HTML tweaking which currently doesn't seem to be possible. As a current workaround, I believe disabling resizing when the tooltip is on the left side is the best course of action. Scrolling is still supported, so users can still get the information they need.

**Comment by winniederidder** [comment]
@pdawyndt The issue on CodeMirror has been closed by the maintainer as "out of scope". The question is thus what our plan is now. Do we want to disable resizing globally and make users work with the scrollbar instead?

**Comment by winniederidder** [comment]
@pdawyndt ?

**Comment by pdawyndt** [comment]
I would keep the resizing option for now. Can we also dismiss scrollbars of the window showing the documentation, if all text is in the viewport? The scrollbars are now shown all the time, as it seems.
