### ISSUE TITLE
Styling Papyros in dark mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#123]
In dark mode: 

- [ ] use same gutter background color in Papyros as with Dodona editor
- [ ] use same syntax highlighting colors as with Dodona editor

![image](https://user-images.githubusercontent.com/5736113/163847784-14b85c52-9d1b-4346-85b2-9aea88198062.png)

Dark mode now uses two different background colors for selections

![image](https://user-images.githubusercontent.com/5736113/163848009-dccfadb3-d42f-4333-95fc-29aa6f4e40df.png)
![image](https://user-images.githubusercontent.com/5736113/163848045-7e37414b-6325-44bc-81ba-c9e73162a16b.png)
![image](https://user-images.githubusercontent.com/5736113/163848067-fbdca889-f54d-483c-9e6e-00fd39fb3a6e.png)

**Comment by winniederidder** [comment]
Using the same syntax highlighting in Papyros as in Dodona will be tricky. Currently, the ace-theme twilight is used. The twilight-theme seems to be available under https://codemirror.net/theme/twilight.css, which is the outdated version of CodeMirror. The version we use is CodeMirror6, which provides the [one-dark](https://github.com/codemirror/theme-one-dark) theme. I will first check if one-dark is not already sufficient for our case. Important to note is also that even if we port the twilight theme to CodeMirror6, there is no guarantee it will be a perfect replica due to interface differences.

**Comment by pdawyndt** [comment]
Having exactly the same highlighting between Ace and CodeMirror is less important than making sure that the dark mode in Papyros looks OK. Definitely don't put any effort yourself in porting themes. Not worth it.
