### ISSUE TITLE
Issues with lots of output

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#17]
The code

```python
for number in range(10000):
    print(number)
```

works the first time you run it on Papyros. However, Papyros stalls the second time you run it. You can still "Terminate" the code though, and run something else. That works fine.

**Comment by winniederidder** [comment]
I've done some experimenting regarding this issue on https://github.com/dodona-edu/papyros/tree/issue17/too-much-output. 
First off, I noticed indeed that the first run works. Looking at the logs, when executing a second time, the code is sent to the worker but not received, so it is not executed. However, after a long time (around 211 seconds), the message did get through. I'm not sure why it blocks, as all the output messages have been successfully delivered.

When only printing 1000 numbers instead of 10000, the problem does not arise, so I figured it has something to do with the amount of messages sent back and forth. In the mentioned branch, I added a queueing system so that print messages are buffered before being sent over to the main thread. However, queue sizes of 100 or 1000 did not solve the problem, the second run still did not get through in a timely fashion.

A potential alternative is just ignoring too much output and notifying the user that further output is not displayed. Perhaps even writing to a file, something Jupyter notebooks do when too much output is generated. But at this moment I don't see a proper solution as I found no helpful information on the internet either regarding too many messages or data being sent.

**Comment by winniederidder** [comment]
@bmesuere @pdawyndt Thoughts on my writings here?

**Comment by pdawyndt** [comment]
We cannot simply ignore lots of output not working. Given the target audience, this will occur.

**Comment by winniederidder** [comment]
I agree, but my research showed that the run-code message seemed to be delayed. I am unsure why this is, and the queueing system I implemented did not solve the issue. The issue is also present in the JavaScript version, so it is not related to Pyodide. It is thus likely to be a Comlink issue, or even something regarding the Messaging system used by WebWorkers (a data or message limit? But queueing would solve the message limit, and I did not find any other clues).
I think we would like to keep displaying messages while running the code, so I can propose the following solutions:
- Hacky and simple: if the code hasn't started running a couple of seconds in, restart the backend and retry.
- Try a file-based solution where large outputs are written to a file instead of displayed (like Jupyter notebooks)
- Ignore displaying long outputs and simply show a truncation warning.

**Comment by alexmojaki** [comment]
I 'solved' this for Python, was it solved elsewhere for JS?

**Comment by winniederidder** [comment]
Indeed, JavaScript still suffers from this issue. Could you elaborate a bit more on how you tackled this problem internally?

**Comment by alexmojaki** [comment]
There's some buffering in https://github.com/alexmojaki/python_runner/blob/master/python_runner/output.py which combines bits of output together so it doesn't trigger the callback for every print. I think you were on the right track above - either comlink or web workers themselves don't handle huge numbers of messages well, and some kind of queue/buffer to reduce the number of messages is probably the solution.
