### ISSUE TITLE
Enable run button faster after switching language 

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#28]
After switching programming language, it takes way too long before the run button gets enabled.

**Comment by pdawyndt** [comment]
Only happens with switching to Python, so apparently some setup needs to be done first?

**Comment by winniederidder** [comment]
Correct, the initialization of the Python worker takes a while as it loads in the standard library and runs some initial code. I don't think our use case involves switching languages often, and the loading time of the worker is only a few seconds. Since users still need to write their code anyway, this doesn't seem to be a real issue?

**Comment by winniederidder** [comment]
Fixed by #112 , the button is clickable faster by not awaiting the loading time up front.
