### ISSUE TITLE
input() prints and returns None

### ISSUE THREAD

**Issue by alexmojaki** [dodona-edu/papyros#56]
Running this code:

```python
print(input() is None)
```

shows this output:

```
None
True
```

1. `input()` **prints** `None` directly, without help from `print()`, which is weird.
2. `input()` **returns** `None` regardless of the actual user input.

**Comment by winniederidder** [comment]
As mentioned in #57, the reason it prints None is because:
- The input callback incorrectly returned None, so this has been fixed
- It prints the value given by the user, similar to how it would be visible in a REPL when a user types his input. If the prompt is empty, this might look a bit confusing. A more clear example is in the attached image (after the above fix).
![input-papyros](https://user-images.githubusercontent.com/53743234/144584015-15efa0d4-20b6-47af-825d-25cfd59954a3.PNG)

**Comment by pdawyndt** [comment]
In the terminal, we might separate input (stdin) from output (stdout) by using different colors, as is done in many REPL (because this is what you mimick here).

**Comment by winniederidder** [comment]
I will create a separate issue for improving the styling in the output area. Color coding is less urgent than this fix, and will also allow room for e.g. styling errors and other messages aswell.
