### ISSUE TITLE
Improve styling of output area

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#58]
Currently, all data in the output area is treated equally. It would be helpful to use different colors for input, output, errors and so forth when displaying those kinds of messages.

**Comment by pdawyndt** [comment]
What about also using CodeMirror for displaying input (stdin) and output (stdout)? Maybe without the line numbers for stdout.

**Comment by winniederidder** [comment]
While theoretically possible, it doesn't sound like the intended purpose since the output doesn't really involve code/programming language items. Might be useful as a fallback if no better options are found.

**Comment by alexmojaki** [comment]
Closely related: it'd be good for the output area to also show stderr. Currently this script just shows `bar`:

```python
import sys
print("foo", file=sys.stderr)
print("bar", file=sys.stdout)
```

Here's how I capture both streams and combine them into one with colors:

https://github.com/alexmojaki/futurecoder/blob/76b24d4f0bacffdea3cdc4ed94190ff3798926e6/core/workers/utils.py#L10-L45

```python
class SysStream:
    def __init__(self, output, color):
        self.output = output
        self.color = color

    def write(self, s):
        # ...skipping some code here...

        self.output.parts.append(
            dict(text=s, color=self.color)
        )

class OutputBuffer:
    def __init__(self):
        self.parts = []
        self.stdout = SysStream(self, "white")
        self.stderr = SysStream(self, "red")
```

https://github.com/alexmojaki/futurecoder/blob/76b24d4f0bacffdea3cdc4ed94190ff3798926e6/core/workers/worker.py#L161

```python
with redirect_stdout(output_buffer.stdout), redirect_stderr(output_buffer.stderr):
```

Then the frontend simply makes a bunch of `span` tags with the color set directly in the style attribute.

For your light background, I imagine stderr in red, stdout in black, and stdin in blue/green/purple.

Then you could send tracebacks to stderr instead of stdout to make them red.

**Comment by winniederidder** [comment]
You raise a good point. For JavaScript, I indeed capture both, so I just forgot for Python. Thanks for this suggestion!
