### ISSUE TITLE
futurecoder

### ISSUE THREAD

**Issue by alexmojaki** [dodona-edu/papyros#63]
[futurecoder](https://futurecoder.io/) has solved many of the problems you're working on. It has an interactive REPL, beginner-friendly tracebacks and linting, and integrated debuggers. The framework for exercises also has many useful features, although I haven't compared to dodona.

What do you think of merging futurecoder and papyros, or integrating the futurecoder IDE into dodona instead of papyros? Then we could combine our efforts to add whatever features you find to be missing from futurecoder, which would hopefully be less work than what you have to do now and would benefit you in the long term.

**Comment by bmesuere** [comment]
Hi Alex,

Thank you for your interest in our project. As you have already figured out, our main project is [Dodona](https://dodona.ugent.be/) (you should be able to sign in if you have an office 365 of gsuite domain). Our focus there is an exercise platform, specifically targeted on secondary and higher education. Teachers can create a course and select from our 8000 exercises and easily follow up the progress of their students. Code submissions of students are queued in our execution environment and run through tests defined by the creator of the exercise. The students then get almost instant feedback on their submissions. Dodona is used extensively at Ghent University, but is also seeing usage from almost all institutions for higher education in Flanders. Since this year, we're seeing an uptake in usage from secondary schools as well. The reason for this is that "computational thinking" is now a mandatory topic in the second grade and many school book publishers use Dodona for their exercises. We not only support Python, but also Java, JavaScript, Haskell, Prolog, C, C#, R, Kotlin, Scheme, mysql and html.

While Dodona works great, many secondary schools have let us know that it is not always straightforward for them to run Python code locally since it-admins are reluctant to install Python and an IDE on school computers. (In my opinion, a full IDE is also not a great match for 14-16 year olds trying Python for the first time). This is why we decided to develop a light-weight alternative to run (basic) Python code in the browser. The goal was then to both offer this as a stand-alone tool/web page, as well as integrate it in our Dodona platform as a "scratchpad" to quickly run some code without submitting a solution. @winniederidder, who has done most of the coding so far, is developing this as his graduation project for his master's degree.

We have of course also seen futurecode in our initial search for existing tools. We were very impressed with the course and set of tools and have drawn some inspiration from it. However, I don't think it is exactly what we're trying to build here. We do have plans to try to integrate birdseye and/or snoop in a later phase of the project. (We already use "Python Tutor" in dodona itself, but are not too happy with the hackish integration we did). That said, I do think it would be valuable to set up a call and discuss things. Please let us know if you would be up for this!

**Comment by winniederidder** [comment]
The key difference is that ultimately Papyros will support not only this functionality for Python, but also for other environments (such as JavaScript, and potentially other languages later on aswell, especially when wasm-support is functional enough). FutureCoder is an amazing project and is very helpful, but I try to design this project in a programming-language independent way. I take your suggestions to heart as they are very insightful, but I do have to consider how to extend some of the approaches (such as friendly_traceback) to a method that could also be beneficial for other languages (such as an interface for the Error objects, with formatting then done by the main thread instead).

**Comment by alexmojaki** [comment]
> you should be able to sign in if you have an office 365 of gsuite domain

Thank you, I didn't realise I could. It took me a few tries to find a suitable account, but I've managed.

> In my opinion, a full IDE is also not a great match for 14-16 year olds trying Python for the first time

I'm curious, what's your opinion of Thonny?

> The goal was then to both offer this as a stand-alone tool/web page, as well as integrate it in our Dodona platform as a "scratchpad" to quickly run some code without submitting a solution.

Ah, if it doesn't need to be connected to the exercise submission/testing system then that should make things much simpler. futurecoder's 'scratchpad' mode (i.e. not showing the course material) is at https://futurecoder.io/course/#ide and I've already been thinking about adding a route (e.g `#embed`) that's a variation on this suitable for embedding as an iframe, basically just removing some elements like the table of contents and login.

However it does make me curious about the purpose of this project. Why not use something like repl.it? Is it just so that users don't have to switch tabs?

> That said, I do think it would be valuable to set up a call and discuss things. Please let us know if you would be up for this!

Absolutely! I live in South Africa so we are almost in the same timezone, and my days are open. I imagine answering the questions I'm piling on now will also be easier in a call.

**Comment by bmesuere** [comment]
I didn't know about Thonny but this indeed in the direction of what I had in mind but browser based.

Why not repl.it? I'm not a user myself, but apparently their free classroom usage is no longer available. In addition, teachers let us know that they would really like something like this integrated in Dodona without the need for a separate account or registration. (We interface with most school systems in Flanders, so no need to create student accounts)

I will discuss this with the rest of the team and get back to you about a meeting on Monday.

**Comment by alexmojaki** [comment]
Here's my plan:

1. I've made a small package https://github.com/alexmojaki/python_runner and factored it out in https://github.com/alexmojaki/futurecoder/pull/248 . It has no dependencies, is meant to be usable in any environment (browser or server) and is meant to deal with the more 'basic' problems like the kind I've been making comments about, particularly on #80. It should be easy to integrate into papyros as is, which I'll happily help with. It should help with #17, replace a bunch of code, and pave the way for future work.
2. I want to make another python package which builds on `python_runner` with support for snoop, birdseye, and better tracebacks. So it's heavier and more opinionated but closer to what futurecoder uses.
3. On the JS side I want to make a very generic npm package for synchronous communication with a web worker using SharedArrayBuffer or service workers, something that can be useful even outside of the Pyodide context. You guys are also using that for the JS backend, right? This fits into #76 
4. Finally I want to put it all together with an npm package interfacing between Pyodide and `python_runner` (with or without the extra dependencies). This should help with #38, #66, and various other things.

**Comment by alexmojaki** [comment]
The bulk of the integration/collaboration is complete! There are still smaller and more specific things in progress or planned, but this issue feels closeable.
